# Generated by Django 3.2.7 on 2021-09-17 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210917_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='resume',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
